// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Data;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AttendanceException", b =>
                {
                    b.Property<int>("ExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ExceptionId"));

                    b.Property<int>("AttendanceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int>("ReportedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ResolvedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.HasKey("ExceptionId")
                        .HasName("PK__Attendan__26981D8886A6E369");

                    b.HasIndex("AttendanceId");

                    b.HasIndex("ReportedBy");

                    b.HasIndex("ResolvedBy");

                    b.ToTable("AttendanceExceptions");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<string>("CheckInMethod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CheckInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckOutMethod")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Present");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69261CBF2CADA3");

                    b.HasIndex("AssignmentId");

                    b.HasIndex(new[] { "EmployeeId" }, "IX_Attendance_Employee");

                    b.HasIndex(new[] { "StoreId" }, "IX_Attendance_Store");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .IsUnicode(false)
                        .HasColumnType("varchar(45)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId")
                        .HasName("PK__AuditLog__EB5F6CBDF6B5B4CE");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Domain.Entities.CashHandover", b =>
                {
                    b.Property<int>("CashHandoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CashHandoverId"));

                    b.Property<decimal?>("ActualCash")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CashierEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal?>("DifferenceAmount")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(19, 2)")
                        .HasComputedColumnSql("(case when `ActualCash` IS NULL then NULL else `ActualCash`-`OpeningFloat` end)", true);

                    b.Property<string>("DifferenceNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("HandoverId")
                        .HasColumnType("int");

                    b.Property<decimal>("OpeningFloat")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("CashHandoverId")
                        .HasName("PK__CashHand__F3BBCA164C9D4280");

                    b.HasIndex("CashierEmployeeId");

                    b.HasIndex("HandoverId");

                    b.ToTable("CashHandovers");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PinHash")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<int>("PrimaryStoreId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04F1113F33E18");

                    b.HasIndex(new[] { "PositionId" }, "IX_Employees_Position");

                    b.HasIndex(new[] { "PrimaryStoreId" }, "IX_Employees_PrimaryStore");

                    b.HasIndex(new[] { "UserId" }, "UQ_Employees_UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "EmployeeCode" }, "UQ__Employee__1F642548DAE225BC")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E12AFE5BF0A");

                    b.HasIndex(new[] { "EmployeeId", "IsRead" }, "IX_Notifications_Employee");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PositionId"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PositionCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("PositionId")
                        .HasName("PK__Position__60BB9A798B32D738");

                    b.HasIndex(new[] { "PositionCode" }, "UQ__Position__83745B020B5CF3B3")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("Domain.Entities.SecurityHandover", b =>
                {
                    b.Property<int>("SecurityHandoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SecurityHandoverId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("HandoverId")
                        .HasColumnType("int");

                    b.Property<int>("ParkingCards")
                        .HasColumnType("int");

                    b.Property<int>("ParkingTickets")
                        .HasColumnType("int");

                    b.Property<bool>("RollerDoorLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("SecurityEmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityNote")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("WarehouseLocked")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("SecurityHandoverId")
                        .HasName("PK__Security__9E160887FF713161");

                    b.HasIndex("HandoverId");

                    b.HasIndex("SecurityEmployeeId");

                    b.ToTable("SecurityHandovers");
                });

            modelBuilder.Entity("Domain.Entities.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOvernight")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ShiftCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("ShiftId")
                        .HasName("PK__Shifts__C0A83881E26348B8");

                    b.HasIndex(new[] { "ShiftCode" }, "UQ__Shifts__9377D56208114F91")
                        .IsUnique();

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Scheduled");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("AssignmentId")
                        .HasName("PK__ShiftAss__32499E77026D4562");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex(new[] { "EmployeeId", "WorkDate" }, "IX_ShiftAssignments_Employee_WorkDate");

                    b.HasIndex(new[] { "StoreId", "WorkDate" }, "IX_ShiftAssignments_Store_WorkDate");

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandoverSession", b =>
                {
                    b.Property<int>("HandoverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("HandoverId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<string>("ManagerNote")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("OpenedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("OpenedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ShiftDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("HandoverId")
                        .HasName("PK__ShiftHan__DB2A1F81EB4E7EA3");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("OpenedBy");

                    b.HasIndex("StoreId");

                    b.ToTable("ShiftHandoverSessions");
                });

            modelBuilder.Entity("Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.Property<int>("SwapRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SwapRequestId"));

                    b.Property<int>("AssignmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RequesterEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TargetEmployeeId")
                        .HasColumnType("int");

                    b.HasKey("SwapRequestId")
                        .HasName("PK__ShiftSwa__EEF5A489E9A0BB3E");

                    b.HasIndex("AssignmentId");

                    b.HasIndex("RequesterEmployeeId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TargetEmployeeId");

                    b.ToTable("ShiftSwapRequests");
                });

            modelBuilder.Entity("Domain.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StoreId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StoreCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("StoreId")
                        .HasName("PK__Stores__3B82F1019E9B97C7");

                    b.HasIndex(new[] { "StoreCode" }, "UQ__Stores__02A384F8D8EB8161")
                        .IsUnique();

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("Domain.Entities.TemporaryDispatch", b =>
                {
                    b.Property<int>("DispatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DispatchId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ApprovedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("FromStoreId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RequestedBy")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("ToStoreId")
                        .HasColumnType("int");

                    b.HasKey("DispatchId")
                        .HasName("PK__Temporar__434DBD5501B43404");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("FromStoreId");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ToStoreId");

                    b.HasIndex(new[] { "EmployeeId", "StartDate", "EndDate" }, "IX_Dispatch_Employee_Date");

                    b.ToTable("TemporaryDispatches");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CD146E62B");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E49C6B9BC8")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("PublishedBy")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<int>("StoreId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("WeekEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WeekStartDate")
                        .HasColumnType("date");

                    b.HasKey("ScheduleId")
                        .HasName("PK__WorkSche__9C8A5B492182D683");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("StoreId");

                    b.ToTable("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceException", b =>
                {
                    b.HasOne("Domain.Entities.AttendanceRecord", "Attendance")
                        .WithMany("AttendanceExceptions")
                        .HasForeignKey("AttendanceId")
                        .IsRequired()
                        .HasConstraintName("FK_Exception_Attendance");

                    b.HasOne("Domain.Entities.Employee", "ReportedByNavigation")
                        .WithMany("AttendanceExceptionReportedByNavigations")
                        .HasForeignKey("ReportedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Exception_Reporter");

                    b.HasOne("Domain.Entities.Employee", "ResolvedByNavigation")
                        .WithMany("AttendanceExceptionResolvedByNavigations")
                        .HasForeignKey("ResolvedBy")
                        .HasConstraintName("FK_Exception_Resolver");

                    b.Navigation("Attendance");

                    b.Navigation("ReportedByNavigation");

                    b.Navigation("ResolvedByNavigation");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceRecord", b =>
                {
                    b.HasOne("Domain.Entities.ShiftAssignment", "Assignment")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Assignment");

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Employee");

                    b.HasOne("Domain.Entities.Store", "Store")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Store");

                    b.Navigation("Assignment");

                    b.Navigation("Employee");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_AuditLogs_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.CashHandover", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "CashierEmployee")
                        .WithMany("CashHandovers")
                        .HasForeignKey("CashierEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_CashHandover_Employee");

                    b.HasOne("Domain.Entities.ShiftHandoverSession", "Handover")
                        .WithMany("CashHandovers")
                        .HasForeignKey("HandoverId")
                        .IsRequired()
                        .HasConstraintName("FK_CashHandover_Session");

                    b.Navigation("CashierEmployee");

                    b.Navigation("Handover");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.Position", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Positions");

                    b.HasOne("Domain.Entities.Store", "PrimaryStore")
                        .WithMany("Employees")
                        .HasForeignKey("PrimaryStoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Employees_Stores");

                    b.HasOne("Domain.Entities.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("Domain.Entities.Employee", "UserId")
                        .HasConstraintName("FK_Employees_Users");

                    b.Navigation("Position");

                    b.Navigation("PrimaryStore");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Notification", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("Notifications")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.SecurityHandover", b =>
                {
                    b.HasOne("Domain.Entities.ShiftHandoverSession", "Handover")
                        .WithMany("SecurityHandovers")
                        .HasForeignKey("HandoverId")
                        .IsRequired()
                        .HasConstraintName("FK_SecurityHandover_Session");

                    b.HasOne("Domain.Entities.Employee", "SecurityEmployee")
                        .WithMany("SecurityHandovers")
                        .HasForeignKey("SecurityEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_SecurityHandover_Employee");

                    b.Navigation("Handover");

                    b.Navigation("SecurityEmployee");
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignments_Employee");

                    b.HasOne("Domain.Entities.WorkSchedule", "Schedule")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignments_Schedule");

                    b.HasOne("Domain.Entities.Shift", "Shift")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ShiftId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignments_Shift");

                    b.HasOne("Domain.Entities.Store", "Store")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftAssignments_Store");

                    b.Navigation("Employee");

                    b.Navigation("Schedule");

                    b.Navigation("Shift");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandoverSession", b =>
                {
                    b.HasOne("Domain.Entities.ShiftAssignment", "Assignment")
                        .WithMany("ShiftHandoverSessions")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_Handover_Assignment");

                    b.HasOne("Domain.Entities.Employee", "ClosedByNavigation")
                        .WithMany("ShiftHandoverSessionClosedByNavigations")
                        .HasForeignKey("ClosedBy")
                        .HasConstraintName("FK_Handover_ClosedBy");

                    b.HasOne("Domain.Entities.Employee", "OpenedByNavigation")
                        .WithMany("ShiftHandoverSessionOpenedByNavigations")
                        .HasForeignKey("OpenedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Handover_OpenedBy");

                    b.HasOne("Domain.Entities.Store", "Store")
                        .WithMany("ShiftHandoverSessions")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Handover_Store");

                    b.Navigation("Assignment");

                    b.Navigation("ClosedByNavigation");

                    b.Navigation("OpenedByNavigation");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.HasOne("Domain.Entities.ShiftAssignment", "Assignment")
                        .WithMany("ShiftSwapRequests")
                        .HasForeignKey("AssignmentId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftSwap_Assignment");

                    b.HasOne("Domain.Entities.Employee", "RequesterEmployee")
                        .WithMany("ShiftSwapRequestRequesterEmployees")
                        .HasForeignKey("RequesterEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftSwap_Requester");

                    b.HasOne("Domain.Entities.Employee", "ReviewedByNavigation")
                        .WithMany("ShiftSwapRequestReviewedByNavigations")
                        .HasForeignKey("ReviewedBy")
                        .HasConstraintName("FK_ShiftSwap_Reviewer");

                    b.HasOne("Domain.Entities.Employee", "TargetEmployee")
                        .WithMany("ShiftSwapRequestTargetEmployees")
                        .HasForeignKey("TargetEmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_ShiftSwap_Target");

                    b.Navigation("Assignment");

                    b.Navigation("RequesterEmployee");

                    b.Navigation("ReviewedByNavigation");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("Domain.Entities.TemporaryDispatch", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "ApprovedByNavigation")
                        .WithMany("TemporaryDispatchApprovedByNavigations")
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("FK_Dispatch_ApprovedBy");

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithMany("TemporaryDispatchEmployees")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Dispatch_Employee");

                    b.HasOne("Domain.Entities.Store", "FromStore")
                        .WithMany("TemporaryDispatchFromStores")
                        .HasForeignKey("FromStoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Dispatch_FromStore");

                    b.HasOne("Domain.Entities.Employee", "RequestedByNavigation")
                        .WithMany("TemporaryDispatchRequestedByNavigations")
                        .HasForeignKey("RequestedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Dispatch_RequestedBy");

                    b.HasOne("Domain.Entities.Store", "ToStore")
                        .WithMany("TemporaryDispatchToStores")
                        .HasForeignKey("ToStoreId")
                        .IsRequired()
                        .HasConstraintName("FK_Dispatch_ToStore");

                    b.Navigation("ApprovedByNavigation");

                    b.Navigation("Employee");

                    b.Navigation("FromStore");

                    b.Navigation("RequestedByNavigation");

                    b.Navigation("ToStore");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Employee", "PublishedByNavigation")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("PublishedBy")
                        .HasConstraintName("FK_WorkSchedules_PublishedBy");

                    b.HasOne("Domain.Entities.Store", "Store")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("StoreId")
                        .IsRequired()
                        .HasConstraintName("FK_WorkSchedules_Stores");

                    b.Navigation("PublishedByNavigation");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceRecord", b =>
                {
                    b.Navigation("AttendanceExceptions");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("AttendanceExceptionReportedByNavigations");

                    b.Navigation("AttendanceExceptionResolvedByNavigations");

                    b.Navigation("AttendanceRecords");

                    b.Navigation("CashHandovers");

                    b.Navigation("Notifications");

                    b.Navigation("SecurityHandovers");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftHandoverSessionClosedByNavigations");

                    b.Navigation("ShiftHandoverSessionOpenedByNavigations");

                    b.Navigation("ShiftSwapRequestRequesterEmployees");

                    b.Navigation("ShiftSwapRequestReviewedByNavigations");

                    b.Navigation("ShiftSwapRequestTargetEmployees");

                    b.Navigation("TemporaryDispatchApprovedByNavigations");

                    b.Navigation("TemporaryDispatchEmployees");

                    b.Navigation("TemporaryDispatchRequestedByNavigations");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Position", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("Domain.Entities.Shift", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("ShiftHandoverSessions");

                    b.Navigation("ShiftSwapRequests");
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandoverSession", b =>
                {
                    b.Navigation("CashHandovers");

                    b.Navigation("SecurityHandovers");
                });

            modelBuilder.Entity("Domain.Entities.Store", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Employees");

                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftHandoverSessions");

                    b.Navigation("TemporaryDispatchFromStores");

                    b.Navigation("TemporaryDispatchToStores");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Navigation("ShiftAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}

