// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shared.Data;

#nullable disable

namespace Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AttendanceLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("AssignmentId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("CheckInPhotoKey")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CheckOutPhotoKey")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("FraudFlaggedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("FraudReason")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsFraudFlagged")
                        .HasColumnType("tinyint(1)");

                    b.Property<ulong?>("KioskId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal?>("OpeningFloatCash")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.HasIndex("FraudFlaggedBy");

                    b.HasIndex("KioskId");

                    b.HasIndex("CheckInTime", "BranchId");

                    b.ToTable("attendance_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BranchCode");

                    b.Property<int>("BranchTier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2)
                        .HasColumnName("BranchTier");
                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GeofenceRadiusMeters")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BranchCode")
                        .IsUnique();

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CashHandover", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("CashierId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("ClosingActualCash")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DiscrepancyReason")
                        .HasColumnType("longtext");

                    b.Property<decimal>("OpeningCash")
                        .HasColumnType("decimal(65,30)");

                    b.Property<ulong>("ShiftHandoverId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("SystemExpectedCash")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("CashierId");

                    b.HasIndex("ShiftHandoverId");

                    b.ToTable("cash_handovers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KioskActivationCode", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("CreatedKioskId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("GeneratedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KioskName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code");

                    b.HasIndex("GeneratedBy");

                    b.ToTable("kiosk_activation_codes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KioskDevice", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("AllowedBrowser")
                        .HasColumnType("longtext")
                        .HasColumnName("AllowedBrowser");

                    b.Property<string>("AllowedIp")
                        .HasColumnType("longtext")
                        .HasColumnName("AllowedIp");

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DeviceToken")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DeviceToken");

                    b.Property<string>("KioskCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LastPingAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("Name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("DeviceToken")
                        .IsUnique();

                    b.HasIndex("KioskCode")
                        .IsUnique();

                    b.ToTable("kiosks", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KioskPairingCode", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PairingCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("PairingCode");

                    b.ToTable("kiosk_pairing_codes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.MonthlyTimesheet", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("ExportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("LockedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("PeriodMonth")
                        .HasColumnType("tinyint unsigned");

                    b.Property<ushort>("PeriodYear")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LockedBy");

                    b.HasIndex("BranchId", "PeriodMonth", "PeriodYear")
                        .IsUnique();

                    b.ToTable("monthly_timesheets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.OvertimeRequest", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("ApprovedByManager")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("ApprovedMinutes")
                        .HasColumnType("int unsigned");

                    b.Property<ulong>("AttendanceLogId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ManagerNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("OtType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RequestedMinutes")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("VerifiedByLeader")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByManager");

                    b.HasIndex("AttendanceLogId");

                    b.HasIndex("VerifiedByLeader");

                    b.ToTable("overtime_requests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SecurityHandover", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsShutterClosed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsWarehouseLocked")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("OvernightVehicleCount")
                        .HasColumnType("smallint unsigned");

                    b.Property<ulong>("SecurityGuardId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("SecurityNotes")
                        .HasColumnType("longtext");

                    b.Property<ulong>("ShiftHandoverId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("SecurityGuardId");

                    b.HasIndex("ShiftHandoverId");

                    b.ToTable("security_handovers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<byte>("AssignedRoleId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("AssignmentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("ScheduleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("AssignedRoleId");

                    b.HasIndex("ScheduleId", "UserId")
                        .IsUnique();

                    b.HasIndex("UserId", "ScheduleId");

                    b.ToTable("shift_assignments", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandover", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("GeneralNotes")
                        .HasColumnType("longtext");

                    b.Property<string>("HandoverStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("ScheduleId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("ShiftLeaderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("SignedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.HasIndex("ShiftLeaderId");

                    b.ToTable("shift_handovers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Reason")
                        .HasColumnType("longtext");

                    b.Property<ulong>("RequestingAssignmentId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("ReviewedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong>("TargetAssignmentId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("RequestingAssignmentId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("TargetAssignmentId");

                    b.ToTable("shift_swap_requests", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShiftTemplate", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("BreakDurationMinutes")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOvernight")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateCode")
                        .IsUnique();

                    b.ToTable("shift_templates", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SystemAuditLog", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("ActorId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<ulong>("TargetId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TargetTable")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.HasIndex("Timestamp", "Action");

                    b.ToTable("system_audit_logs", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TemporaryDispatch", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong?>("ApprovedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<ulong>("RequestedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("SourceBranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("TargetBranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("SourceBranchId");

                    b.HasIndex("TargetBranchId");

                    b.HasIndex("UserId", "StartDate", "EndDate", "Status");

                    b.ToTable("temporary_dispatches", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmployeeCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<ulong?>("HomeBranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("KioskPinHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<byte>("RoleId")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmployeeCode")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("HomeBranchId", "Status");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<ulong>("BranchId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<byte>("RequiredCashier")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("RequiredSales")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("RequiredSecurity")
                        .HasColumnType("tinyint unsigned");

                    b.Property<uint>("ShiftTemplateId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ShiftTemplateId");

                    b.HasIndex("BranchId", "ShiftTemplateId", "WorkDate")
                        .IsUnique();

                    b.HasIndex("BranchId", "WorkDate", "Status");

                    b.ToTable("work_schedules", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AttendanceLog", b =>
                {
                    b.HasOne("Domain.Entities.ShiftAssignment", "Assignment")
                        .WithOne("AttendanceLog")
                        .HasForeignKey("Domain.Entities.AttendanceLog", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "FraudFlaggedByUser")
                        .WithMany()
                        .HasForeignKey("FraudFlaggedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.KioskDevice", "Kiosk")
                        .WithMany()
                        .HasForeignKey("KioskId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Assignment");

                    b.Navigation("Branch");

                    b.Navigation("FraudFlaggedByUser");

                    b.Navigation("Kiosk");
                });

            modelBuilder.Entity("Domain.Entities.CashHandover", b =>
                {
                    b.HasOne("Domain.Entities.User", "Cashier")
                        .WithMany()
                        .HasForeignKey("CashierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ShiftHandover", "ShiftHandover")
                        .WithMany("CashHandovers")
                        .HasForeignKey("ShiftHandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cashier");

                    b.Navigation("ShiftHandover");
                });

            modelBuilder.Entity("Domain.Entities.KioskActivationCode", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("Domain.Entities.KioskDevice", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany("Kiosks")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Domain.Entities.KioskPairingCode", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Domain.Entities.MonthlyTimesheet", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "LockedByUser")
                        .WithMany()
                        .HasForeignKey("LockedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Branch");

                    b.Navigation("LockedByUser");
                });

            modelBuilder.Entity("Domain.Entities.OvertimeRequest", b =>
                {
                    b.HasOne("Domain.Entities.User", "ApprovedByManagerUser")
                        .WithMany()
                        .HasForeignKey("ApprovedByManager")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.AttendanceLog", "AttendanceLog")
                        .WithMany("OvertimeRequests")
                        .HasForeignKey("AttendanceLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "VerifiedByLeaderUser")
                        .WithMany()
                        .HasForeignKey("VerifiedByLeader")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovedByManagerUser");

                    b.Navigation("AttendanceLog");

                    b.Navigation("VerifiedByLeaderUser");
                });

            modelBuilder.Entity("Domain.Entities.SecurityHandover", b =>
                {
                    b.HasOne("Domain.Entities.User", "SecurityGuard")
                        .WithMany()
                        .HasForeignKey("SecurityGuardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ShiftHandover", "ShiftHandover")
                        .WithMany("SecurityHandovers")
                        .HasForeignKey("ShiftHandoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecurityGuard");

                    b.Navigation("ShiftHandover");
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Role", "AssignedRole")
                        .WithMany()
                        .HasForeignKey("AssignedRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.WorkSchedule", "Schedule")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("ShiftAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedRole");

                    b.Navigation("Schedule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandover", b =>
                {
                    b.HasOne("Domain.Entities.WorkSchedule", "Schedule")
                        .WithOne("ShiftHandover")
                        .HasForeignKey("Domain.Entities.ShiftHandover", "ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "ShiftLeader")
                        .WithMany()
                        .HasForeignKey("ShiftLeaderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("ShiftLeader");
                });

            modelBuilder.Entity("Domain.Entities.ShiftSwapRequest", b =>
                {
                    b.HasOne("Domain.Entities.ShiftAssignment", "RequestingAssignment")
                        .WithMany()
                        .HasForeignKey("RequestingAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "ReviewedByUser")
                        .WithMany()
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.ShiftAssignment", "TargetAssignment")
                        .WithMany()
                        .HasForeignKey("TargetAssignmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequestingAssignment");

                    b.Navigation("ReviewedByUser");

                    b.Navigation("TargetAssignment");
                });

            modelBuilder.Entity("Domain.Entities.SystemAuditLog", b =>
                {
                    b.HasOne("Domain.Entities.User", "Actor")
                        .WithMany()
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("Domain.Entities.TemporaryDispatch", b =>
                {
                    b.HasOne("Domain.Entities.User", "ApprovedByUser")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.User", "RequestedByUser")
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Branch", "SourceBranch")
                        .WithMany()
                        .HasForeignKey("SourceBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Branch", "TargetBranch")
                        .WithMany()
                        .HasForeignKey("TargetBranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByUser");

                    b.Navigation("RequestedByUser");

                    b.Navigation("SourceBranch");

                    b.Navigation("TargetBranch");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "HomeBranch")
                        .WithMany("Users")
                        .HasForeignKey("HomeBranchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HomeBranch");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.HasOne("Domain.Entities.Branch", "Branch")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.ShiftTemplate", "ShiftTemplate")
                        .WithMany("WorkSchedules")
                        .HasForeignKey("ShiftTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("CreatedByUser");

                    b.Navigation("ShiftTemplate");
                });

            modelBuilder.Entity("Domain.Entities.AttendanceLog", b =>
                {
                    b.Navigation("OvertimeRequests");
                });

            modelBuilder.Entity("Domain.Entities.Branch", b =>
                {
                    b.Navigation("Kiosks");

                    b.Navigation("Users");

                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.ShiftAssignment", b =>
                {
                    b.Navigation("AttendanceLog");
                });

            modelBuilder.Entity("Domain.Entities.ShiftHandover", b =>
                {
                    b.Navigation("CashHandovers");

                    b.Navigation("SecurityHandovers");
                });

            modelBuilder.Entity("Domain.Entities.ShiftTemplate", b =>
                {
                    b.Navigation("WorkSchedules");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("ShiftAssignments");
                });

            modelBuilder.Entity("Domain.Entities.WorkSchedule", b =>
                {
                    b.Navigation("ShiftAssignments");

                    b.Navigation("ShiftHandover");
                });
#pragma warning restore 612, 618
        }
    }
}
